apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-ui
  namespace: test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx  
  tls:
    - hosts:
        - student-ui.shinejohnk.xyz
      secretName: student-ui-tls
  rules:
    - host: student-ui.shinejohnk.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: student-ui
                port:
                  number: 80
